### PR TITLE
homekit: map EntrySensor to homekit ContactSensor

### PR DESCRIPTION
**Pull request by billyzoellers**
Door/open close sensor in ZWave is a ScryptedInterface.EntrySensor which was not supported by homekit

### CODE REVIEW

**Comment by koush** [comment]
doesn't it also expose a binarysensor which is exposed? usually zwave does both.

**Comment by billyzoellers** [comment]
In this case, no. It's an Aeotec Refressed Door Sensor 7

```
> device.interfaces
[
  'Battery',
  'EntrySensor',
  'Online',
  'PowerSensor',
  'Refresh',
  'Settings',
  'mixin:@scrypted/homekit'
]
```

**Comment by koush** [comment]
Multiple contact sensors will need unique names to prevent HAP service clash. See how I handled the audio sensor type in the same file.

**Comment by billyzoellers** [comment]
Updated to avoid that. Do your door sensors present both BinarySensor and EntrySensor? If so, this probably causes a duplicate in HomeKit.

**Comment by koush** [comment]
I think they do. You could add it only if a binary sensor isn’t found.

**Comment by billyzoellers** [comment]
Should be good now.

**Pull request merged**
