### PR TITLE
synology-ss: make login more resilient

### LINKED ISSUE #1266: When Scrypted Docker container is getting updated, connection is lost with Synology Surveillance Station
**Describe the bug**
Every time the Scrypted docker container is updated by watchtower, the synology plugin seems to be not able to reconnect by itself to Synology Surveillance Station.
The plugin indicates that the logon timeout of 10000 ms has been exceeded.

When I click on "reload plugin", everything goes back to normal again and Scrypted is able to connect without issue to Surveillance Station.

**To Reproduce**
Let watchtower update the docker container.
Upon container restart, Scrypted is unable to connect immediately to Surveillance Station.
Click on "Reload plugin" from the plugin page for Synology
All goes back to normal

**Expected behavior**
Reconnection after upgrade should be automatic and flawless

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
- OS : Synology DSM 7.2.1-69057 Update 3 (Latest to date)
- Running in docker container (official image) inside Synology Container Manager
- Scrypted versions that showed the defect (that I noticed) : 0.80;0.81;0.82;0.83

### PR DESCRIPTION
**Pull request by IGx89**
Fixes #1266

### CODE REVIEW

**Comment by IGx89** [comment]
@koush thank you! I'm getting a 404 unfortunately when attempting to publish it. Would you be able to publish it for me, or re-grant me permission to publish it myself?

**Comment by koush** [comment]
what is your npm? I dont recall removing your access from anything

**Comment by koush** [comment]
found it, done

**Comment by IGx89** [comment]
That did the trick, published! Thanks again :)

**Pull request merged**
