### PR TITLE
Initial version of Doorbird plugin

### PR DESCRIPTION
**Pull request by nanosonde**
This is a new plugin for Doorbird video doorbell stations: https://www.doorbird.com/
The plugin will use the API that is documented by the manufacturer here: https://www.doorbird.com/downloads/api_lan.pdf
It will use this NPM module to receive doorbell and motion sensor events: https://github.com/ihrigb/node-doorbird

**WORKING:**
- receive video stream (720p @ 10 FPS) via unencrypted RTSP
- receive audio stream (8000 Hz, 1 channel, PCM uLaw) via unencrypted HTTP calls to audio-receive.cgi
- sending audio to the doorbell speaker via documented HTTP calls to audio-transmit.cgi endpoint.
- event handling for doorbell button and motion sensor using the existing NPM module (see above).

**TODO:**
- ~improve security by using session ID token via encrypted HTTPS calls to getsession.cgi and use this session ID (valid for 10 minutes only) to access unencrypted HTTP. UPDATE: see issue [here]( https://github.com/ihrigb/node-doorbird/issues/73)~

Concerning security:
- Doorbird RTSP server supports standard RTSP authentication schemes: BASIC and DIGEST.
So when using RTSP DIGEST via FFMPEG this should be safe as FFMPEG supports RTSP DIGEST auth. 
- For the audio receiver we use FFMPEG with the HTTP module. The HTTP module should also support DIGEST auth. So it should be safe. 
- The audio transmitter uses HTTP DIGEST via AXIOS. So this should be safe too.

"Safe" here means: no password in cleartext over the wire. No man-in-the-middle-attack protection, etc.

### CODE REVIEW

**Comment by koush** [comment]
> * sending audio to the doorbell speaker via documented HTTP calls to audio-transmit.cgi endpoint.

hikvision and amcrest plugins have examples of how to do this using Scrypted's internal stream handling libraries.

**Comment by nanosonde** [comment]
@koush 
I have tested the plugin in the current state and everything is working as exptected.
I have modified the initial comment of this PR, please see the new text. Especially, the cancelled ToDo.
Maybe this could be added later.

I won't have the time to continue working on this in the next weeks.
For me, it works good enough in my production env.

**Comment by mbrackjr** [comment]
@koush ; if you can pull this request and make it available as a docker image I will surely test this; would be awesome if we finally get Doorbird doorbell as a native homekit enabled doorbell.

**Comment by michaelyork** [comment]
This is huge! Thank you to the original contributor and @koush for reviewing. I will test tomorrow as well.

**Comment by michaelyork** [comment]
Confirming the plugin is working flawlessly in my environment across 4 different units in 2 locations. Only wish is for it to continuously stream audio (vs. only when in 2-way-talk mode), but I recognize the DoorBird API may be the limiting factor there.

Thanks again @nanosonde!

**Comment by mbrackjr** [comment]
Also on my end confirmation that plugin works fine. Awesome to finally have bidirectional audio working in Apple native Home app.  The only thing that did not work for me was the doorbell triggering. I've resolved it for now by embedding doorbird device into a grouped device including a webhook that acts as doorbell override, but would very much welcome that that functionality gets included into the plugin natively.
Thanks @nanosonde for your effort of the plugin and @koush for awesome scrypted app.

**Comment by michaelyork** [comment]
Hmm, doorbell functionality working for me.

**Comment by nanosonde** [comment]
> The only thing that did not work for me was the doorbell triggering. 

Could you please try reoading the plugin and watch the console log of the plugin? Any errors?
If the plugin ist started, a listening UDP socket is created thats listens for the event messages that are broadcasted by the Doorbird station.

I wonder if the UDP socket could be opened. Do you have other Doorbird related software running on the same host as scrypted? Assuming that it is running in docker host networking mode.

Maybe you could also use wireshark or tcpdump to watch out for those UDP broadcasts. Do you see any from the IP of your Doorbird?

**Comment by mbrackjr** [comment]
Apologies; mistyped the UDP portnumber in my hosts' iptables....  Doorbell now works within the plugin.  

I seem to be having issues with HKSV though; added a motion sensor (external one) and reference that in the homekit configuration. I see in the logs it tries to start recording, but nothing shows up in my home app eventually. Below the log-lines if you're able/willing to help troubleshoot.  The three (i have 3 homepod minis) "timed out" warnings are the problem it seems.

Awesome plugin nonetheless!

```
scrypted  | device 77 Deurbel Beweging
scrypted  |
scrypted  | i Deurbel Beweging on: true
scrypted  | i Deurbel Beweging lockState: Unlocked
scrypted  | i Deurbel Beweging running: true
scrypted  | i Deurbel Beweging motionDetected: true
scrypted  | i Deurbel Beweging binaryState: true
scrypted  | i Deurbel Beweging occupied: true
scrypted  | [Deurbel] HomeKit Connection 192.168.0.222
scrypted  |
scrypted  | [Deurbel] Deurbel recording session starting ::ffff:192.168.0.222 {
scrypted  |   mediaContainerConfiguration: { prebufferLength: 4000, type: 0, fragmentLength: 4000 },
scrypted  |   videoCodec: {
scrypted  |     type: 0,
scrypted  |     bitrate: 800,
scrypted  |     level: 2,
scrypted  |     profile: 0,
scrypted  |     resolution: [ 1920, 1080, 30 ],
scrypted  |     iFrameInterval: 4000
scrypted  |   },
scrypted  |   audioCodec: {
scrypted  |     audioChannels: 1,
scrypted  |     type: 0,
scrypted  |     samplerate: 3,
scrypted  |     bitrateMode: 0,
scrypted  |     bitrate: 64
scrypted  |   }
scrypted  | }
scrypted  |
scrypted  | [Deurbel] HomeKit Connection 192.168.0.220
scrypted  |
scrypted  | [Deurbel] Deurbel recording session starting ::ffff:192.168.0.220 {
scrypted  |   mediaContainerConfiguration: { prebufferLength: 4000, type: 0, fragmentLength: 4000 },
scrypted  |   videoCodec: {
scrypted  |     type: 0,
scrypted  |     bitrate: 800,
scrypted  |     level: 2,
scrypted  |     profile: 0,
scrypted  |     resolution: [ 1920, 1080, 30 ],
scrypted  |     iFrameInterval: 4000
scrypted  |   },
scrypted  |   audioCodec: {
scrypted  |     audioChannels: 1,
scrypted  |     type: 0,
scrypted  |     samplerate: 3,
scrypted  |     bitrateMode: 0,
scrypted  |     bitrate: 64
scrypted  |   }
scrypted  | }
scrypted  |
scrypted  | [Deurbel] Deurbel recording session starting ::ffff:192.168.0.221 {
scrypted  |   mediaContainerConfiguration: { prebufferLength: 4000, type: 0, fragmentLength: 4000 },
scrypted  |   videoCodec: {
scrypted  |     type: 0,
scrypted  |     bitrate: 800,
scrypted  |     level: 2,
scrypted  |     profile: 0,
scrypted  |     resolution: [ 1920, 1080, 30 ],
scrypted  |     iFrameInterval: 4000
scrypted  |   },
scrypted  |   audioCodec: {
scrypted  |     audioChannels: 1,
scrypted  |     type: 0,
scrypted  |     samplerate: 3,
scrypted  |     bitrateMode: 0,
scrypted  |     bitrate: 64
scrypted  |   }
scrypted  | }
scrypted  |
scrypted  | Doorbird: timed out waiting for tcp client from ffmpeg
scrypted  |
scrypted  | Doorbird: timed out waiting for tcp client from ffmpeg
scrypted  |
scrypted  | Doorbird: timed out waiting for tcp client from ffmpeg
scrypted  |
scrypted  | i Deurbel Beweging on: false
scrypted  | i Deurbel Beweging lockState: Locked
scrypted  | i Deurbel Beweging running: false
scrypted  | i Deurbel Beweging motionDetected: false
scrypted  | i Deurbel Beweging binaryState: false
scrypted  | i Deurbel Beweging occupied: false
```

**Comment by nanosonde** [comment]
@mbrackjr 
I recommend that you enable the transcoding plugin for the doorbird.
And then enable at least transcoding of the remote recording stream.
Without this I had no success either.

**Comment by mbrackjr** [comment]
@nanosonde ; that did the trick indeed.   Thanks again for making this happen; my faith in getting Doorbird fully functional working in Homekit was almost gone!

**Pull request merged**
